import type { OrderStatus } from '@zepto/types';
export declare const FREE_DELIVERY_THRESHOLD = 199;
export declare const DELIVERY_FEE = 29;
export declare const WALLET_MIN_TOPUP = 10;
export declare const WALLET_MAX_TOPUP = 10000;
export declare const OTP_EXPIRY_SECONDS = 60;
export declare const OTP_DEV = "123456";
export declare const REFRESH_TOKEN_EXPIRY_DAYS = 7;
export declare const ACCESS_TOKEN_EXPIRY_MINUTES = 15;
export declare const DEFAULT_PAGE = 1;
export declare const DEFAULT_LIMIT = 20;
export declare const MAX_LIMIT = 50;
export declare const CACHE_TTL_FEATURED_PRODUCTS = 300;
export declare const CACHE_TTL_CATEGORIES = 600;
export declare const CACHE_TTL_WALLET = 30;
export declare const ORDER_STATUS_FLOW: Record<OrderStatus, OrderStatus[]>;
export declare const CANCELLABLE_STATUSES: OrderStatus[];
export declare const ORDER_STATUS_LABELS: Record<OrderStatus, string>;
export declare const ORDER_STATUS_COLORS: Record<OrderStatus, string>;
export declare const APP_NAME = "Zepto";
export declare const APP_TAGLINE = "10-minute grocery delivery";
export declare const SEARCH_DEBOUNCE_MS = 300;
export declare const RECENTLY_VIEWED_LIMIT = 10;
